
export enum MessageTypeEnumVd { ERROR = 'ERROR', INFO = 'INFO', SUCCESS = 'SUCCESS', WARNING = 'WARNING' };
export enum EditActionEnumVd { CHANGE_STATUS = 'CHANGE_STATUS', DELETE = 'DELETE', SYNC = 'SYNC', UPDATE = 'UPDATE', CREATE = 'CREATE' };
export enum ClientOperationEnumVd { INIT_DELETE_FORM = 'INIT_DELETE_FORM', INIT_SEARCH_FORM = 'INIT_SEARCH_FORM', VALIDATE_FORM = 'VALIDATE_FORM', INIT_UPDATE_FORM = 'INIT_UPDATE_FORM', INIT_CHANGE_STATUS_FORM = 'INIT_CHANGE_STATUS_FORM', INIT_CREATE_FORM = 'INIT_CREATE_FORM' };