
export enum TransactionTypeEnumVd { DEBIT = 'DEBIT', DEPOT = 'DEPOT', CREDIT = 'CREDIT', DEPENSE = 'DEPENSE', RETRAIT = 'RETRAIT', RECETTE = 'RECETTE' };
export enum CompteTypeEnumVd { EMPLOYE = 'EMPLOYE', GENERAL = 'GENERAL', CLIENT = 'CLIENT', FOURNISSEUR = 'FOURNISSEUR' };
export enum TransactionStatusEnumVd { ANNULEE = 'ANNULEE', APPROUVEE = 'APPROUVEE', RESERVEE = 'RESERVEE', ENCOURS = 'ENCOURS', CLOTUREE = 'CLOTUREE' };