
export enum TransactionTypeEnumVd { DEPOT = 'DEPOT', DEPENSE = 'DEPENSE', RETRAIT = 'RETRAIT', RECETTE = 'RECETTE' };
export enum TransactionStatusEnumVd { ANNULEE = 'ANNULEE', APPROUVEE = 'APPROUVEE', RESERVEE = 'RESERVEE', ENCOURS = 'ENCOURS', CLOTUREE = 'CLOTUREE' };