spring: 
   application:
      name: agro360-web
   jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate.ddl-auto: none
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/agro360_dev3
      username: agro360
      password: Agr0360Today       
   devtools:
      add-properties: true
      livereload:
         enabled: true       
   http:
      multipart:
         max-file-size: 10MB
         max-request-size: 11MB
server:
   port: 8080
   

jwt.secret: bigmwaj
front.url: http://localhost:4200
   